### PR TITLE
mkerlimage: adjust to work with FreeBSD 12.2

### PR DESCRIPTION
**Pull request by infrastation**

### CODE REVIEW

**Comment by ndorf** [comment]
Thanks.

Heads up, MIPS support is likely going away in future versions of FreeBSD: https://lists.freebsd.org/archives/freebsd-arch/2021-September/index.html#msg51

**Comment by infrastation** [comment]
I could argue pro and contra at some length, but in this context I am just a user, and it is up to the developers which architectures to support. Anyway, even if 12.2 is the last version to boot on ERLite-3, it helps to have a working script to generate the disk image, so here you go.

**Comment by ndorf** [comment]
Yes, this change is definitely needed, thank you. I didn't mean to imply otherwise.

**Comment by infrastation** [comment]
Thank you for merging this quickly.

**Pull request merged**
